### ISSUE TITLE
Use in a cluster

### ISSUE THREAD

**Issue by jeremyscrivener** [Acosix/alfresco-audit#4]
Hi Axel, 

When running an ACS cluster, does this plugin need to be run on all nodes in the cluster or can it be run on a single node?

Cheers,

Jeremy

**Comment by AFaust** [comment]
As the addon provides distributed caching capabilities it must be run on all ACS nodes within a cluster / distributed cache grid, otherwise there would be no way the state of the various caches in Alfresco can be kept in sync / consistent.

Technically speaking though, the plugin could be run on only individual nodes in very specific use cases:

- disabled aldica cache factory (using Alfresco default caches) and Ignite only used to create an / connect to an abritrary grid for purposes other than caching (absolutely not documented in the context of aldica and currently an unintended use)
- (future version of aldica) enabled aldica cache factory with all data caches set to a `null` cache, meaning read-through operations

**Comment by jeremyscrivener** [comment]
Thanks Axel - we're just wanting to use the OOTB activeusers/inactiveusers reports. Would these cover activity on all nodes, even if the audit plugin is only installed on one?

**Comment by AFaust** [comment]
No, definitely not. The active / inactive user reports is based on an auditing configuration packaged in the addon and requiring custom Java components that it would not be accurate if only run on one server - you would simply miss out any activity on any other server. The custom auditing configuration and component are necessary because Alfresco by default does not have a reliable means to track all active users - only users who actively perform changes, and using an out-of-the-box audit configuration (alfresco-access) that records way too much data for only this specific purpose.

Deploying the addon on only one server would be valid in a use case where you only want to use its incremental cleanup functionality, as that can safely be run on only one server.

**Comment by jeremyscrivener** [comment]
Thanks for the clarification!
